### PR TITLE
Added error handling to the dynamic UI pages

### PR DESCRIPTION
**Pull request by antoninguerre**
- Added error and success messages to the UI when an axios method is called.
- Added console.log statements to see success and error messages in the console.
- Disabled buttons when there are unfilled text fields.
- Added an admin password check to prevent users from reaching the ban/unban accounts page (we will remove it once we 
have the admin UI working)
- Added support for localStorage in some UI pages.
- Fixed typos.

### CODE REVIEW

**Comment by antoninguerre** [comment]
closes #60

**Comment by antoninguerre** [comment]
https://user-images.githubusercontent.com/71234445/141535479-253e89ff-c0be-4b15-b37c-c4c2514712b4.mov

**Comment by antoninguerre** [comment]
https://user-images.githubusercontent.com/71234445/141535717-2414b3af-582a-49d8-bf40-069d355cbcd8.mov

Other sign in page error message and successful account deletion message

**Review by JulietteDebray — APPROVED** [review]
beaut

**Review by Salman-Mesam — APPROVED** [review]
Looks crispy to me!

**Review by Salman-Mesam — APPROVED** [review]
Looks crispy to me!

**Pull request merged**
